
name: Windows-RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Setup Ngrok & Enable RDP
        run: |
          iwr -useb https://raw.githubusercontent.com/0xw0lf/WinRDP/main/rdp.ps1 | iex
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
