name: FreeRDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download and start RDP
        run: |
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/GitHackTools/Windows-10-Cloud-RDP/main/cloudshell-win.ps1 -OutFile rdp.ps1
          powershell -ExecutionPolicy Bypass -File rdp.ps1
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

